import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  // Navigation
  "Recent Logins": "最近登錄",
  "Network Usage": "網路流量",
  "Xray IP Stats": "Xray IP 統計",
  "App Config": "應用配置",
  "Analytics": "儀表盤",
  "TalkPro Users": "TalkPro 用戶",
  "First Login Time": "創建時間（第一次登錄時間）",
  "Last Ping": "最後 Ping 時間",
  "Last Ping Details": "最後 Ping 詳情",

  // Network Usage
  "Network IP": "網路 IP",
  "User": "用戶",
  "Last Updated": "最後更新",
  "Total Sent": "總發送量",
  "Total Received": "總接收量",
  "Mobile Data": "行動數據",
  "WiFi Data": "WiFi 數據",
  "Details": "詳情",
  "View Stats": "查看統計",
  "View Details": "查看詳情",
  "Foreground Status": "前台狀態",
  "All Traffic": "所有流量",
  "Foreground Only": "僅前台",
  "Background Only": "僅後台",
  "Total Sent / Received": "發送 / 接收總計",
  "App Usage Statistics": "應用使用統計",
  "Active Users Today": "今日活躍用戶",
  "Total Users": "總用戶數",
  "Total Data Sent (All-Time):": "總數據發送 (歷史總計):",
  "Total Data Received (All-Time):": "總數據接收 (歷史總計):",
  "Top User (Data Volume):": "流量最高用戶:",
  "Preferred Network Type:": "首選網路類型:",
  "Users": "用戶",
  "All Pings": "所有 Ping",
  "By User (Current)": "按用戶查看 (最新)",
  "By Time (Historical)": "按時間查看 (歷史)",
  "View Raw DB Data": "查看原始數據",
  "Raw MongoDB Telemetries (Buckets)": "原始 MongoDB 遙測數據 (Buckets)",
  "Date": "日期",
  "Date/Time": "日期 / 時間",
  "Flush Old Pings (Keep Latest)": "清理舊 Ping 記錄 (保留最新)",
  "Are you sure you want to flush old network pings while keeping the latest ping per user?": "您確定要清理舊的網路 Ping 記錄，並保留每個用戶的最新記錄嗎？",
  "Successfully flushed": "成功清理了",
  "old records (retention period:": "條舊記錄 (保留期:",
  "days).": "天)。",
  "Failed to flush:": "清理失敗:",
  "Error flushing records.": "清理記錄時出錯。",
  "Enter data retention days (documents older than this will be deleted, keeping the latest per user):": "請輸入數據保留天數 (早於此天數的數據將被刪除，且保留每個用戶的最新記錄):",
  "Please enter a valid number of days.": "請輸入有效的保留天數。",

  // Xray
  "Active Xray Proxy Servers": "活躍的 Xray 代理服務器",
  "Proxy IP": "代理 IP",
  "Active Users": "活躍用戶",
  "Total Sent (All-Time)": "總發送 (歷史總計)",
  "Total Received (All-Time)": "總接收 (歷史總計)",
  "Connected Users": "已連接用戶",
  "Xray IP": "Xray IP",
  "No Xray proxy data available yet.": "暫無 Xray 代理數據。",

  // Logins
  "Network IPs": "網路 IP",
  "Time": "時間",
  "Device": "設備",
  "VPN?": "是否使用 VPN?",
  "Emulator": "模擬器",
  "No logins recorded yet.": "暫無登錄記錄。",

  // Configs
  "App Version Configuration": "應用版本配置",
  "App Version Configuration (Android)": "應用版本配置 (Android)",
  "App Version Configuration (iOS)": "應用版本配置 (iOS)",
  "Configure update metrics served at /api/android/version": "配置提供於 /api/android/version 的 Android 更新指標",
  "Configure update metrics served at /api/ios/version": "配置提供於 /api/ios/version 的 iOS 更新指標",
  "Version Code": "版本號 (Code)",
  "Version Name": "版本名 (Name)",
  "Download URL": "下載連結",
  "Changelog": "更新日誌",
  "Require Force Update": "要求強制更新",
  "Save Configuration": "保存配置",
  "VersionCode": "版本號 (Code)",
  "VersionName": "版本名 (Name)",
  "DownloadUrl": "下載連結",
  "ForceUpdate": "要求強制更新",
  "XRAY Node IPs": "Xray 節點 IP",
  "Manage the list of XRAY node IPs served at": "管理 Xray 節點 IP 列表提供於",
  "+ Add IP Address": "+ 新增 IP 地址",
  "Remarks / Scratchpad": "備註 / 草稿本",
  "Save XRAY IPs & Remarks": "保存 Xray IP 與備註",
  "XRAY IPs & Remarks saved successfully!": "Xray IP 與備註保存成功！",
  "Available Endpoints": "可用 API 端點",
  "Configuration saved successfully!": "配置保存成功！",
  "Failed to save configuration.": "配置保存失敗。",
  "Error loading configuration.": "加載配置出錯。",
  "Failed to load current version data.": "加載當前版本數據失敗。",
  "No Xray IPs configured. Click \"+ Add IP Address\" to get started.": "尚未配置 Xray IP。點擊「+ 新增 IP 地址」開始配置。",
  "Failed to load Xray IPs.": "加載 Xray IP 失敗。",
  "Error loading Xray IPs.": "加載 Xray IP 出錯。",
  "Failed to save Xray IPs.": "保存 Xray IP 失敗。",
  "Error saving Xray IPs.": "保存 Xray IP 出錯。",

  // MT Proxies
  "MT Proxies": "MT 代理",
  "No MT Proxies configured. Click \"+ Add Proxy\" to get started.": "尚未配置 MT 代理。點擊「+ 新增代理」開始配置。",
  "Host (e.g. 13.212.194.160)": "主機 (例如 13.212.194.160)",
  "Port (e.g. 443)": "端口 (例如 443)",
  "Secret (hex)": "密鑰 (hex)",
  "+ Add Proxy": "+ 新增代理",
  "Paste notes, backup config strings, or scratchpad text here...": "在此處貼上筆記、備用配置字元或草稿文本...",
  "Save MT Proxies & Remarks": "保存 MT 代理與備註",
  "MT Proxies & Remarks saved successfully!": "MT 代理與備註保存成功！",
  "Failed to save MT Proxies.": "保存 MT 代理失敗。",
  "Error saving MT Proxies.": "保存 MT 代理出錯。",

  // Analytics
  "TalkPro Telemetry - Analytics": "TalkPro 遙測 - 儀表盤",
  "Network Statistics": "網路統計",
  "Daily Network Statistics": "每日網路統計",
  "Daily Active Users": "每日活躍用戶",
  "Daily New Users": "每日新增用戶",
  "Active Users (Period)": "活躍用戶 (所選期間)",
  "Active Users (Foreground Only)": "活躍用戶 (僅前台)",
  "Active Users (Foreground + Background)": "活躍用戶 (前台+後台)",
  "Foreground only": "僅前台",
  "Users with at least one foreground ping": "新版本 至少打开一次 的用戶數量",
  "Background only": "僅後台",
  "Users with strictly background pings only": "新版本 在後台運行 但並未打開 的用戶數量",
  "Non-applicable": "不適用",
  "Users using legacy app clients": "使用舊版客戶端的用戶",
  "Classification Definitions:": "分類定義說明:",
  "Users with at least one foreground ping in this period.": "在此期間內，至少有一次前台運行的活躍用戶。",
  "Users with strictly background pings only in this period.": "在此期間內，完全僅在後台運行的活躍用戶。",
  "Users using legacy app clients without foreground flags.": "使用未支援前台狀態上報之舊版客戶端的用戶。",
  "Users who registered their very first ping in this period.": "在此期間內，首次註冊歷史遙測記錄的新用戶。",
  "New Users": "新用戶",
  "New Users (Period)": "新增用戶 (所選期間)",
  "Total Users (All-time)": "總用戶數 (歷史)",
  "Includes VPN/Proxy": "包含 VPN/代理流量",
  "Avg Total Upload / User": "平均用戶總發送流量",
  "Avg Total Download / User": "平均用戶總接收流量",
  "Avg Daily Upload / User": "平均用戶單日發送",
  "Avg Daily Download / User": "平均用戶單日接收",
  "Avg Upload / User (Period)": "平均用戶發送 (所選期間)",
  "Avg Download / User (Period)": "平均用戶接收 (所選期間)",
  "Avg Upload / User (Period) (Excl. Top 10)": "平均用戶發送 去除 Top 10 (所選期間)",
  "Avg Download / User (Period) (Excl. Top 10)": "平均用戶接收 去除 Top 10 (所選期間)",
  "Total Combined Traffic (Period)": "用戶總發送與接收 (所選期間)",
  "Total Combined Traffic (Period) (Excl. Top 10)": "用戶總發送與接收 去除 Top 10 (所選期間)",
  "Estimated Cost": "預估流量費用",
  "out of {count} members": "共 {count} 位成員",
  "Top 20 Users by Traffic": "前 20 名流量用戶",
  "Traffic": "流量",
  "Cost": "費用",
  "Usage Days": "使用天數",

  // Timeframes
  "Latest Ping": "最新 Ping",
  "Last 15 Mins": "過去 15 分鐘",
  "Last Hour": "過去一小時",
  "Today": "今天",
  "Yesterday": "昨天",
  "This Week": "本週",
  "All Time": "歷史總計",

  // General / Misc
  "Loading...": "加載中...",
  "Unknown": "未知",
  "English": "English",
  "中文": "中文",
  "Logout": "登出",
  "Switch to iOS Backend": "切換至 iOS 後端",
  "Switch to Android Backend": "切換至 Android 後端",
  "Change Password": "修改密碼",
  "Delete": "刪除",
  "Actions": "操作",
  "Role": "角色",
  "Username": "用戶名",
  "Password": "密碼",
  "Add User": "添加用戶",
  "Add New User": "添加新用戶",
  "Staff": "員工",
  "Admin": "管理員",
  "Save": "保存",
  "Saving...": "保存中...",
  "Updating...": "更新中...",
  "Failed to load user list": "加載用戶列表失敗",
  "You do not have permission to view users.": "您沒有查看用戶的權限。",

  // Traffic Report
  "Traffic Report": "流量報告",
  "All Users": "所有用戶",
  "All Xray IPs": "所有 Xray IP",
  "Interval": "時間間隔",
  "Export Report": "匯出報告",
  "Mobile vs WiFi": "行動數據 vs WiFi",
  "Ping Success Rate": "Ping 成功率",
  "Usage Alert": "用量警報",
  "Heavy Traffic Alert (>= 500MB)": "高流量警報 (>= 500MB)",
  "Detailed Traffic Report Dashboard": "詳細流量報告控制面板",
  "Timeline Charts": "時間線圖表",
  "Users Breakdown": "用戶細分",
  "Xray Proxy Breakdown": "Xray 代理細分",
  "Download CSV": "下載 CSV",
  "Copy CSV": "複製 CSV",
  "Mobile Upload": "行動發送",
  "Mobile Download": "行動接收",
  "WiFi Upload": "WiFi 發送",
  "WiFi Download": "WiFi 接收",
  "Uplink / Downlink Traffic": "上傳 / 下載流量",
  "Server Health & Failure Rates": "服務器健康度與失敗率",
  "Failure Rate": "失敗率",
  "Total Pings": "Ping 總數",
  "Failed Pings": "失敗 Ping 數",
  "Xray IP Health Indicator": "Xray IP 健康指標",
  "Search logs...": "搜尋記錄...",
  "Active Users on proxy:": "此代理上的活躍用戶:",
  "Total": "總計",
  "pings": "次 Ping",
  "Failed": "失敗",
  "No timeline telemetry logged for this period.": "此期間無時間線遙測記錄。",
  "Total Traffic": "總流量",
  "Top Users by Data Consumption": "數據消耗排名前五用戶",
  "No user traffic data recorded.": "無用戶流量數據記錄。",
  "Top Xray Proxy Servers": "Xray 代理服務器排名前五",
  "Success": "成功",
  "No Xray active pings recorded.": "無 Xray 活躍 Ping 記錄。",
  "User Data Analysis Grid": "用戶數據分析網格",
  "Red background flags represent active account connections routing >= 500MB total data volume.": "紅色背景標記代表總數據流量大於或等於 500MB 的活躍帳戶連接。",
  "Total Consumption": "總用量",
  "Network split (Mob / WiFi)": "網路分流 (行動 / WiFi)",
  "No users matched search parameters.": "無符合搜尋條件的用戶。",
  "Xray Server Health Summary": "Xray 服務器健康度摘要",
  "Proxy active IPs registering a ping failure rate exceeding 15% are flagged with orange warnings for connection instability.": "Ping 失敗率超過 15% 的代理活躍 IP 將被標記為橙色警告，表示連接不穩定。",
  "Total Bytes Sent": "總發送字節",
  "Total Bytes Received": "總接收字節",
  "Combined Traffic": "合併流量",
  "Success Rate / Total pings": "成功率 / 總 Ping 次數",
  "Status Badge": "狀態標籤",
  "of": "次 / 總計",
  "Excellent": "優秀",
  "Warning": "警告",
  "Poor Health": "健康度差",
  "No Xray proxy metrics registered.": "無 Xray 代理指標註冊。",
  "Custom Report Spreadsheet Exporter": "自定義報告導出器",
  "Export formatted telemetry log matrices in CSV or Clipboard layout formats.": "導出 CSV 格式或剪貼板佈局格式的格式化遙測記錄矩陣。",
  "User ID": "用戶 ID",
  "Display Name": "顯示名稱",
  "Total Volume": "總量",
  "Mobile Share": "行動數據佔比",
  "WiFi Share": "WiFi 佔比",
  "User Telemetry Details": "用戶遙測詳情",
  "Mobile Usage": "行動數據用量",
  "WiFi Usage": "WiFi 用量",
  "Usage History Timeline": "使用歷史時間線",
  "No timelines recorded for this user.": "此用戶無記錄時間線。",
  "Mob": "行動數據",
  "WiFi": "WiFi",
  "Proxies Routed Through": "經由的代理服務器",
  "No active proxies recorded for this user.": "此用戶無活躍代理記錄。",
  "Error loading data.": "加載數據出錯。",
  "Proxy Server Details": "代理服務器詳情",
  "Ping Health Rate": "Ping 健康率",
  "Traffic Timeline History": "流量時間線歷史",
  "No timelines recorded for this proxy server.": "此代理服務器無記錄時間線。",
  "No active users routed through this IP for the period.": "此期間無活躍用戶經由該 IP。"
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'zh');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (text) => {
    if (lang === 'zh') {
      return translations[text] || text;
    }
    return text;
  };

  const toggleLang = () => {
    setLang((prev) => (prev === 'en' ? 'zh' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
